#!/bin/sh

set -e

# iptables chain prefix
N=quortus

forwarding=yes
mode=nat
hooks=yes

usage() {
    cat <<EOF
$0 [--no-forwarding] [--mode routed] [--no-hooks]

    --no-forwarding  Don't enable IP forwarding (default: enable)
    --mode           Select "routed" or "nat" mode (default: nat)
    --no-hooks       Don't add hooks in main iptables chains (default: add)
EOF
}

while [ $# -gt 0 ]; do
    case "$1" in
      --help)
        usage
        exit 0
      ;;
      --forwarding)
        forwarding=yes
        shift
      ;;
      --no-forwarding)
        forwarding=no
        shift
      ;;
      --mode)
        case "$2" in
          nat|routed)
            mode="$2"
            shift 2
          ;;
          *)
            usage >&2
            echo "Invalid mode $2" >&2
            exit 1
          ;;
        esac
      ;;
      --hooks)
        hooks=yes
        shift
      ;;
      --no-hooks)
        hooks=no
        shift
      ;;
      *)
        usage >&2
        exit 1
      ;;
    esac
done

enable_forwarding() {
    sysctl net.ipv4.ip_forward=1 >/dev/null
    #sysctl net.ipv6.conf.default.forwarding=1 >/dev/null
    #sysctl net.ipv6.conf.all.forwarding=1 >/dev/null
}

if [ $forwarding = yes ]; then
    enable_forwarding
fi

setup_iptables() {
    # default gateway
    out_if="$(ip route | sed -n '/^default /s/.* dev \([^ ]*\).*/\1/p')"

    # prepare chains
    iptables -N $N-FORWARD 2>/dev/null || true
    iptables -F $N-FORWARD 2>/dev/null || true

    iptables -t nat -N $N-POSTROUTING 2>/dev/null || true
    iptables -t nat -F $N-POSTROUTING 2>/dev/null || true

    # NAT specific rules
    if [ $mode = nat ]; then
        iptables -t nat -A $N-POSTROUTING -o "$out_if" -j MASQUERADE
    fi

    # add hooks in main chains
    if [ $hooks = yes ]; then
        # TODO add source IP specifier
        iptables -t nat -D POSTROUTING -j $N-POSTROUTING 2>/dev/null || true
        iptables -t nat -A POSTROUTING -j $N-POSTROUTING

        iptables -D FORWARD -j $N-FORWARD 2>/dev/null || true
        iptables -A FORWARD -j $N-FORWARD
    fi
}

setup_iptables

