#!/bin/sh

set -e

enable_forwarding() {
    sysctl net.ipv4.ip_forward=1 >/dev/null
    #sysctl net.ipv6.conf.default.forwarding=1 >/dev/null
    #sysctl net.ipv6.conf.all.forwarding=1 >/dev/null
}

enable_forwarding

