#!/bin/sh

set -e

# IP forwarding is required both for NAT and routed use cases
enable_forwarding() {
    sysctl net.ipv4.ip_forward=1
}

# create iptables chains hooking into main ones
setup_iptables() {
    local out_if="$(ip route | sed -n '/^default /s/.* dev \([^ ]*\).*/\1/p')"

    # prepare chain
    iptables -N quortus-postrouting || true
    iptables -F quortus-postrouting || true
    # NAT mode
    iptables -A quortus-postrouting -o "$out_if" -j MASQUERADE
    # jump from main chain to this one
    # TODO add source IP specifier
    iptables -t nat -D POSTROUTING -j quortus-postrouting || true
    iptables -t nat -A POSTROUTING -j quortus-postrouting

    # TODO add forward rules
}

enable_forwarding
setup_iptables

